### PR TITLE
Discord and Github Verification steps

### PR DESCRIPTION
**Pull request by Danko2111**
This PR creates two new MD files that will outline the steps to verify both platforms respectively.

### CODE REVIEW

**Comment by CloudEllie** [comment]
@SamusElderg wdyt about adding the Github verification steps here to the [warden auth docs](https://docs.code4rena.com/roles/wardens/warden-auth#discord-verification)?

**Comment by SamusElderg** [comment]
> @SamusElderg wdyt about adding the Github verification steps here to the [warden auth docs](https://docs.code4rena.com/roles/wardens/warden-auth#discord-verification)?

I read that section of the docs (albeit the title: `Authenticate with your wallet` is a bit misleading) as 'account setup' and Github verification isnt really apart of that, but we can add it there and make sure we mention that its optional?

**Comment by CloudEllie** [comment]
> the title: Authenticate with your wallet is a bit misleading

Agree, should we change to "Register a warden account"?

> Github verification isnt really apart of that, but we can add it there and make sure we mention that its optional

True, but it seems the most logical place to include it, unless you have other suggestions.

**Comment by SamusElderg** [comment]
> Agree, should we change to "Register a warden account"?

Id maybe go as generic as even just "Register Code4rena account" 

> True, but it seems the most logical place to include it, unless you have other suggestions.

Ill have other suggestions later once we do a refresh of the docs code/layout 👍 for now it definitely seems like the best place for it other than maybe a page that talks about 'certification' (or both)

**Comment by CloudEllie** [comment]
Closing this - will set up a new PR that includes GH verification

**Pull request closed without merging**
